- name: Deploy simple HTML page
  hosts: webservers
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy index.html to webserver
      copy:
        src: index.html
        dest: /data/semaphore/index.html

    - name: Start Nginx
      service:
        name: nginx
        state: started
        
    # Tasks to manage groups
    - name: Ensure the 'developers' group exists
      group:
        name: developers
        state: present

    - name: Ensure the 'ops' group exists
      group:
        name: ops
        state: present

    # Tasks to manage users
    - name: Ensure the user 'alice' exists
      user:
        name: alice
        groups: developers
        state: present
        create_home: yes

    - name: Ensure the user 'bob' exists
      user:
        name: bob
        groups: ops
        state: present
        create_home: yes
